name: daylight
description: Get the sunset and sunrise times for a geolocation without having to access any api.
version: 2.0.0
homepage: https://github.com/renancaraujo/daylight

environment:
  sdk: ">=2.12.0 <3.0.1"

dependencies:
  intl: ^0.18.0
  angles: ^2.1.1

dev_dependencies:
  test: ^1.24.2